### ISSUE TITLE
StringOutOfBoundsException error on macOS

### ISSUE THREAD

**Issue by Foadsf** [MyLibreLab/MyLibreLab#1]
Running the `/distribution/start_macosx` [file](https://github.com/MyLibreLab/MyLibreLab/blob/master/distribution/start_macosx) on macOS I get the error:

<pre>
Exception in thread "main" java.lang.StringOutOfBoundsException: begin 2, end 3, length2
              at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3756)
              at java.base/java.lang.String.substring(String.java:1902)
              at VisualLogic.FrameMain.initApp(FrameMain.java:1112)
              at VisualLogic.FrameMain.<init>(FrameMain.java:1538)
              at VisualLogic.FrameMain.main(FrameMain.java:2273)
</pre>

<pre>
<img src="https://user-images.githubusercontent.com/12762442/79600707-e1a97000-80e7-11ea-996a-1d91367a437b.png" width="600">               
</pre>

also posted [here on Reddit](https://www.reddit.com/r/javahelp/comments/g375tc/javalangstringindexoutofboundsexception_when/?utm_source=share&utm_medium=web2x)

**Comment by Foadsf** [comment]
Now I get the error

<pre>
Exception in thread "main" java.lang.NullPointerException
                         at VisualLogic.Tools.listDrivers(Tools.java:321)
                         at VisualLogic.FrameMain.<init>(FrameMain.java:1538)
                         at VisualLogic.FrameMain.main(FrameMain.java:2260)
</pre>

which is caused by the exact same line:

    frm = new FrameMain(args);

**Comment by Mare70** [comment]
This issue was fixed when we migrated to java 14, it can be closed now.
