### ISSUE TITLE
NullPointerException and ClosedChannelException when opening and editing vlogic files

### ISSUE THREAD

**Issue by alehel** [MyLibreLab/MyLibreLab#41]
On Windows 10, using the latest changes from dev and JDK 11, I get a number of NullPointerExceptions and ClosedChannelExceptions when I open a vlogic file. This seems to happen regardless of which file I open. The two exceptions occur several times, but all seem to be the same problem. 

Bellow is one of the NullPointerExceptions.
<details><summary><code>Couldn't create Element :java.lang.NullPointerException
2020-10-05 08:59:25 [SwingWorker-pool-1-thread-3] VisualLogic.Element.loadFromStream()
ERROR: java.lang.NullPointerException</summary>
	at Peditor.PropertyEditor.addItem(PropertyEditor.java:1224)
	at VisualLogic.Element.jAddPEItem(Element.java:1677)
	at Const.setPropertyEditor(Const.java:111)
	at VisualLogic.Element.loadProperties(Element.java:878)
	at VisualLogic.Element.loadFromStream(Element.java:1042)
	at VisualLogic.VMObject.readElements(VMObject.java:3234)
	at VisualLogic.VMObject.loadFromStream(VMObject.java:3431)
	at VisualLogic.Basis.loadFromStream(Basis.java:1817)
	at VisualLogic.Basis.loadFile(Basis.java:1388)
	at VisualLogic.Basis.loadFromFile(Basis.java:1459)
	at VisualLogic.FrameMain.addBasisToVMPanel(FrameMain.java:1023)
	at VisualLogic.FrameMain$1.doInBackground(FrameMain.java:429)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Error in Element.loadFromStream() :java.lang.NullPointerException</code></details>

and bellow is one of the ClosedChannelExceptions:

<details><summary><code>java.io.IOException: Stream Closed
2020-10-05 08:59:26 [SwingWorker-pool-1-thread-3] SimpleFileSystem.FileSystemOutput.addIndexList()
ERROR: java.nio.channels.ClosedChannelException</summary>
	at java.base/sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:156)
	at java.base/sun.nio.ch.FileChannelImpl.position(FileChannelImpl.java:331)
	at SimpleFileSystem.FileSystemOutput.addIndexList(FileSystemOutput.java:99)
	at SimpleFileSystem.FileSystemOutput.close(FileSystemOutput.java:123)
	at VisualLogic.Basis.saveFile(Basis.java:1989)
	at VisualLogic.Basis.saveForUndoRedo(Basis.java:1491)
	at VisualLogic.FrameMain.XaddBasisToVMPanel(FrameMain.java:946)
	at VisualLogic.FrameMain.addBasisToVMPanel(FrameMain.java:1032)
	at VisualLogic.FrameMain$1.doInBackground(FrameMain.java:429)
	at java.desktop/javax.swing.SwingWorker$1.call(SwingWorker.java:304)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.desktop/javax.swing.SwingWorker.run(SwingWorker.java:343)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)</code></details>

I've attached a file with the entire stacktrace. 
[stacktrace.txt](https://github.com/MyLibreLab/MyLibreLab/files/5325763/stacktrace.txt)

I get the same ClosedChannelException if I attempt to add anything to the file, for instance an Oval.

I first discovered this yesterday when I cloned the project for the first time.

**Comment by weisJ** [comment]
Instead of fixing this particular exception being thrown the "project management" portion is a good candidate of being rewritten entirely. Having a good infrastructure of handling information about the current open project/workspace helps a lot in later development.

**Comment by alehel** [comment]
This problem seems to show up pretty much regardless of what I try and do 😆 . For instance, if I open Bin2Dec.Demo.vlogic and run the vm, no matter which button I click, I get the following.

<details><summary><code>Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException</summary>
	at TasterPanel.mousePressed(TasterPanel.java:190)
	at tools.JVSMain.xonMousePressed(JVSMain.java:185)
	at BasisStatus.StatusRun.mousePressed(StatusRun.java:129)
	at VisualLogic.VMObject.elementMousePressed(VMObject.java:2970)
	at VisualLogic.Element.mousePressed(Element.java:2841)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6633)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at VisualLogic.Element.processMouseEvent(Element.java:3408)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4545)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at TasterPanel.mouseReleased(TasterPanel.java:174)
	at tools.JVSMain.xonMouseReleased(JVSMain.java:187)
	at BasisStatus.StatusRun.mouseReleased(StatusRun.java:154)
	at VisualLogic.VMObject.elementMouseReleased(VMObject.java:2964)
	at VisualLogic.Element.mouseReleased(Element.java:2831)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at VisualLogic.Element.processMouseEvent(Element.java:3408)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)</code></details>

**Comment by marko-radosavljevic** [comment]
Some pointers I can give for now, that are maybe useful for debugging:

1. Commit without this issue is 77527097. You can do `git checkout 77527097` to look around.
2. Visual bug I have on my 'buntu 20.04 machine, caused by this issue I believe, looks like [this](https://i.imgur.com/XpUfOpG.png). `JSplitPane`should use more sane defaults even without this issue imo..
3. You can find original archived MyOpenLab version [here](https://github.com/MyLibreLab/MyOpenLab).

**Comment by ElGreenoProgramador** [comment]
What I found about this problem is in `vmobject.owner.isLoading()` @ 1224, as pointed by @alehel and here `owner` is null, and this is called inside a new thread. Maybe owner has not been already initialized at the moment for the call?

**Comment by marko-radosavljevic** [comment]
But im with @weisJ on this one. We shouldn't get stuck maintaining legacy code. Whole module is bad? Swap it out with good and maintained dependency, or refactor/rewrite the whole thing.
