### ISSUE TITLE
Liesmich.html not found

### ISSUE THREAD

**Issue by alehel** [MyLibreLab/MyLibreLab#42]
When selecting _Help -> Info_ in the application, an error message appears stating that it cannot find the file Liesmich.html.
![image](https://user-images.githubusercontent.com/22277624/95055197-3de26980-06f3-11eb-9015-9d2ac4a2fcc6.png)
![image](https://user-images.githubusercontent.com/22277624/95054734-9cf3ae80-06f2-11eb-87ce-1e3508386e7b.png)
and the following stacktrace is shown,
>2020-10-05 10:10:09 [AWT-EventQueue-0] VisualLogic.FrameInfo.<init>()
ERROR: java.io.IOException: invalid url
	at java.desktop/javax.swing.JEditorPane.setPage(JEditorPane.java:416)
	at VisualLogic.FrameInfo.<init>(FrameInfo.java:138)
	at VisualLogic.FrameMain.showInfo(FrameMain.java:5341)
	at VisualLogic.FrameMain.jmiInfoActionPerformed(FrameMain.java:5614)
	at VisualLogic.FrameMain$98.actionPerformed(FrameMain.java:3449)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

As a result, the tab for the license shows an empty text box.

![image](https://user-images.githubusercontent.com/22277624/95054933-e3490d80-06f2-11eb-9d8d-a57f607384df.png)

I propose that we fix this by including a file called license.txt which contains the GPL-3.0 license text.

**Comment by weisJ** [comment]
Yes for sure. As I am currently rewriting the UI I already had to do this for the licence dialog that shows when first launching the application. I am going to open a PR with my changes this evening so we can coordinate a bit better. I wouldn’t want there to be multiple places resources are located/ multiple methods to load them.
